import { useTranslation } from 'react-i18next';
function LesmillsPrograms() {
	const { t, i18n } = useTranslation('programs');
	const lesMillsPrograms = {
		[t('cat1.title')]: [
			{
				title: 'BODYPUMP',
				logo: '/classLogo/BODYPUMP.png',
				picture: '',
				id: 'BODYPUMP',
				sum: t('cat1.program1.sum'),
				description: t('cat1.program1.description'),
				whyMember: t('cat1.program1.whyMember'),
				whyYou: t('cat1.program1.whyYou'),
				type: t('cat1.program1.type'),
				lessons: t('cat1.program1.lessons'),
				equipment: t('cat1.program1.equipment'),
				for: t('cat1.program1.for'),
				result: t('cat1.program1.result'),
			},
			{
				title: 'BODYCOMBAT',
				logo: '/classLogo/BODYCOMBAT.png',
				picture: '',
				id: 'BODYCOMBAT',
				sum: t('cat1.program2.sum'),
				description: t('cat1.program2.description'),
				whyMember: t('cat1.program2.whyMember'),
				whyYou: t('cat1.program2.whyYou'),
				type: t('cat1.program2.type'),
				lessons: t('cat1.program2.lessons'),
				equipment: t('cat1.program2.equipment'),
				for: t('cat1.program2.for'),
				result: t('cat1.program2.result'),
			},
			{
				title: 'LES MILLS BODYBALANCE',
				logo: '/classLogo/BODYBALANCE.png',
				picture: '',
				id: 'LES-MILLS-BODYBALANCE',
				sum: t('cat1.program3.sum'),
				description: t('cat1.program3.description'),
				whyMember: t('cat1.program3.whyMember'),
				whyYou: t('cat1.program3.whyYou'),
				type: t('cat1.program3.type'),
				lessons: t('cat1.program3.lessons'),
				equipment: t('cat1.program3.equipment'),
				for: t('cat1.program3.for'),
				result: t('cat1.program3.result'),
			},
			{
				title: 'LES MILLS CORE',
				logo: '/classLogo/CORE.png',
				picture: '',
				id: 'LES-MILLS-CORE',
				sum: t('cat1.program4.sum'),
				description: t('cat1.program4.description'),
				whyMember: t('cat1.program4.whyMember'),
				whyYou: t('cat1.program4.whyYou'),
				type: t('cat1.program4.type'),
				lessons: t('cat1.program4.lessons'),
				equipment: t('cat1.program4.equipment'),
				for: t('cat1.program4.for'),
				result: t('cat1.program4.result'),
			},
			{
				title: 'BODYATTACK',
				logo: '/classLogo/BODYATTACK.png',
				picture: '',
				id: 'BODYATTACK',
				sum: t('cat1.program5.sum'),
				description: t('cat1.program5.description'),
				whyMember: t('cat1.program5.whyMember'),
				whyYou: t('cat1.program5.whyYou'),
				type: t('cat1.program5.type'),
				lessons: t('cat1.program5.lessons'),
				equipment: t('cat1.program5.equipment'),
				for: t('cat1.program5.for'),
				result: t('cat1.program5.result'),
			},
			{
				title: 'RPM',
				logo: '/classLogo/RPM.png',
				picture: '',
				id: 'RPM',
				sum: t('cat1.program6.sum'),
				description: t('cat1.program6.description'),
				whyMember: t('cat1.program6.whyMember'),
				whyYou: t('cat1.program6.whyYou'),
				type: t('cat1.program6.type'),
				lessons: t('cat1.program6.lessons'),
				equipment: t('cat1.program6.equipment'),
				for: t('cat1.program6.for'),
				result: t('cat1.program6.result'),
			},
			{
				title: 'SH’BAM',
				logo: '/classLogo/SH’BAM.png',
				picture: '',
				id: 'SH’BAM',
				sum: t('cat1.program7.sum'),
				description: t('cat1.program7.description'),
				whyMember: t('cat1.program7.whyMember'),
				whyYou: t('cat1.program7.whyYou'),
				type: t('cat1.program7.type'),
				lessons: t('cat1.program7.lessons'),
				equipment: t('cat1.program7.equipment'),
				for: t('cat1.program7.for'),
				result: t('cat1.program7.result'),
			},
			{
				title: 'BODYJAM',
				logo: '/classLogo/BODYJAM.png',
				picture: '',
				id: 'BODYJAM',
				sum: t('cat1.program8.sum'),
				description: t('cat1.program8.description'),
				whyMember: t('cat1.program8.whyMember'),
				whyYou: t('cat1.program8.whyYou'),
				type: t('cat1.program8.type'),
				lessons: t('cat1.program8.lessons'),
				equipment: t('cat1.program8.equipment'),
				for: t('cat1.program8.for'),
				result: t('cat1.program8.result'),
			},
			{
				title: 'BODYSTEP',
				logo: '/classLogo/BODYSTEP.png',
				picture: '',
				id: 'BODYSTEP',
				sum: t('cat1.program9.sum'),
				description: t('cat1.program9.description'),
				whyMember: t('cat1.program9.whyMember'),
				whyYou: t('cat1.program9.whyYou'),
				type: t('cat1.program9.type'),
				lessons: t('cat1.program9.lessons'),
				equipment: t('cat1.program9.equipment'),
				for: t('cat1.program9.for'),
				result: t('cat1.program9.result'),
			},
			{
				title: 'LES MILLS TONE',
				logo: '/classLogo/TONE.png',
				picture: '',
				id: 'LES-MILLS-TONE',
				sum: t('cat1.program10.sum'),
				description: t('cat1.program10.description'),
				whyMember: t('cat1.program10.whyMember'),
				whyYou: t('cat1.program10.whyYou'),
				type: t('cat1.program10.type'),
				lessons: t('cat1.program10.lessons'),
				equipment: t('cat1.program10.equipment'),
				for: t('cat1.program10.for'),
				result: t('cat1.program10.result'),
			},
			{
				title: 'THE TRIP',
				logo: '/classLogo/THE-TRIP.png',
				picture: '',
				id: 'THE-TRIP',
				sum: t('cat1.program11.sum'),
				description: t('cat1.program11.description'),
				whyMember: t('cat1.program11.whyMember'),
				whyYou: t('cat1.program11.whyYou'),
				type: t('cat1.program11.type'),
				lessons: t('cat1.program11.lessons'),
				equipment: t('cat1.program11.equipment'),
				for: t('cat1.program11.for'),
				result: t('cat1.program11.result'),
			},
			{
				title: 'LES MILLS BARRE',
				logo: '/classLogo/BARRE.png',
				picture: '',
				id: 'LES-MILLS-BARRE',
				sum: t('cat1.program12.sum'),
				description: t('cat1.program12.description'),
				whyMember: t('cat1.program12.whyMember'),
				whyYou: t('cat1.program12.whyYou'),
				type: t('cat1.program12.type'),
				lessons: t('cat1.program12.lessons'),
				equipment: t('cat1.program12.equipment'),
				for: t('cat1.program12.for'),
				result: t('cat1.program12.result'),
			},
		],
		[t('cat2.title')]: [
			{
				title: 'BORN TO MOVE',
				logo: '/classLogo/BORNTOMOVE.png',
				picture: '',
				id: 'BORN-TO-MOVE',
				subTitles: [
					`BORN TO MOVE 2-3 ${t('cat2.program1.subTitle')}`,
					`BORN TO MOVE 4-5 ${t('cat2.program1.subTitle')}`,
					`BORN TO MOVE 6-7 ${t('cat2.program1.subTitle')}`,
					`BORN TO MOVE 8-12 ${t('cat2.program1.subTitle')}`,
					`BORN TO MOVE 13-16 ${t('cat2.program1.subTitle')}`,
				],
				sum: t('cat2.program1.sum'),
				description: t('cat2.program1.description'),
				why: t('cat2.program1.why'),
				type: t('cat2.program1.type'),
				lessons: t('cat2.program1.lessons'),
				equipment: t('cat2.program1.equipment'),
				for: t('cat2.program1.for'),
				result: t('cat2.program1.result'),
			},
		],
		[t('cat3.title')]: [
			{
				title: 'LES MILLS SPRINT',
				logo: '/classLogo/SPRINT.png',
				picture: '',
				id: 'LES-MILLS-SPRINT',
				sum: t('cat3.program1.sum'),
				description: t('cat3.program1.description'),
				whyMember: t('cat3.program1.whyMember'),
				whyYou: t('cat3.program1.whyYou'),
				type: t('cat3.program1.type'),
				lessons: t('cat3.program1.lessons'),
				equipment: t('cat3.program1.equipment'),
				for: t('cat3.program1.for'),
				result: t('cat3.program1.result'),
			},
			{
				title: 'LES MILLS GRIT',
				logo: '/classLogo/GRIT.png',
				picture: '',
				id: 'LES-MILLS-GRIT',
				subTitles: ['GRIT Strenght', 'GRIT Cardio', 'GRIT Athletic'],
				sum: t('cat3.program2.sum'),
				description: t('cat3.program2.description'),
				whyMember: t('cat3.program2.whyMember'),
				whyYou: t('cat3.program2.whyYou'),
				type: t('cat3.program2.type'),
				lessons: t('cat3.program2.lessons'),
				equipment: t('cat3.program2.equipment'),
				for: t('cat3.program2.for'),
				result: t('cat3.program2.result'),
			},
		],
	};
	return lesMillsPrograms;
}
export default LesmillsPrograms;
